### ISSUE TITLE
Intégrer les icônes des labels et des pictos

### ISSUE THREAD

**Issue by arnaudlevy** [ensembleatable/icons#1]
- [ ] en svg, avec le code normalisé
- [ ] en font si c'est une bonne idée

**Comment by arnaudlevy** [comment]
@SebouChu t'as le code de la norme sous le coude ?

**Comment by SebouChu** [comment]
EN 14916:2006
https://cdn.standards.iteh.ai/samples/9104/d57ca98b1f644424a68ef582a427db70/SIST-EN-14916-2006.pdf

**Comment by SebouChu** [comment]
https://staging.ensembleatable.fr/admin/pictograms
